
name: CI Gestion bodega con Java Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configuración JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Compilación de cada microservicio
      - name: Compilar microservicio 'gestion-usuarios'
        run: cd gestion-usuarios && ./mvnw clean install

      - name: Compilar microservicio 'gestion-inventarios'
        run: cd gestion-inventarios && ./mvnw clean install

      - name: Compilar microservicio 'registro-entrada-salida'
        run: cd registro-entrada-salida && ./mvnw clean install

      - name: Compilar microservicio 'gestion-pedidos'
        run: cd gestion-pedidos && ./mvnw clean install

      - name: Compilar microservicio 'integracion-proveedores'
        run: cd integracion-proveedores && ./mvnw clean install

      - name: Compilar microservicio 'monitoreo-sistema'
        run: cd monitoreo-sistema && ./mvnw clean install

      - name: Compilar microservicio 'gestion-mantenimiento'
        run: cd gestion-mantenimiento && ./mvnw clean install

      - name: Compilar microservicio 'validacion-usuario'
        run: cd validacion-usuario && ./mvnw clean install

      - name: Compilar microservicio 'auditoria-y-logs'
        run: cd auditoria-y-logs && ./mvnw clean install

      - name: Compilar microservicio 'notificaciones'
        run: cd notificaciones && ./mvnw clean install

